### ISSUE TITLE
Problem with the filter

### ISSUE THREAD

**Issue by ffcc** [mbaez/elastic-lists#1]
When a filter is done and then an item of the filtered list is selected, the filter is removed from the input. The problem is that if the item is deselected, the filter made before selection is maintained even when the input filter is empty.

**Comment by mbaez** [comment]
Local search uses CSS selectors, instead of Jquery show / hide for performance improved. The problem is that the rules are not deleted after the event 'on-click' was triggered. There is a[ new release](https://github.com/mbaez/elastic-lists/releases/tag/v0.0.2) that resolves this issue .

**Comment by ffcc** [comment]
Oima leka, oikoite la nde rekaka jajaja
