### ISSUE TITLE
Using ID in columns

### ISSUE THREAD

**Issue by ffcc** [mbaez/elastic-lists#2]
Is there a way to configure an ID for a column? I need something like this:

```
var el = new ElasticList({
      el: $('#el-id'),
      data: data,
      countColumn: 'total',
      columns: [{
        title: 'Title',
        attr: 'descriptionColumn',
        id: 'idColumn'
      }]
    });
```

Another option that I seem is the use of render or formatters functions:

```
columns: [{
    title: 'Title',
    attr: 'idColumn',
    (render|formatter): function (val) {
        return val + ' - ' + completeData[val].descriptionColumn;
    }
}];
```

I need to use on this way because the attr can be repeated if I use the descriptionColumn, and have to be displayed the descriptionColumn.

**Comment by mbaez** [comment]
Hi @ffcc  currently there is a method that is responsible for formatting the data. the method was modified to receive the first item that matches the value of the column. This will be available in the next release.

``` javascript
columns:[{
    title: "Country",
    attr: "col_country",
    formatter : function(value, first){ 
      value = value.toUpperCase();
      return value;
    }
  },
  ...
]
```
